version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8001 --workers 3 core.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:01"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web_1

volumes:
  postgres_data:
  static_volume:
  media_volume: